---
linters:
  disable:
    # deprecated
    - ifshort
    - nosnakecase
    - scopelint
    # We love TODOs
    - godox
    # not sure how to fix things
    - forbidigo
    # Too crazy to use
    - depguard
    - exhaustive
    - exhaustruct
    - gochecknoinits
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused
  # Run only fast linters from enabled linters set (first run won't be fast)
  # Default: false
  # fast: true
linters-settings:
  lll:
    line-length: 128
  varnamelen:
    ignore-decls:
      - c echo.Context
      - const C
      - e error
      - i int
      - m map[string]int
      - ok bool
      - s string
      - T any
      - t testing.T
  wsl:
    # Allow blocks to end with comments.
    allow-trailing-comment: true
issues:
  exclude-rules:
    - path: "internal/provider"
      linters:
        - dupl
