---
# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - binary: goer
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      # - arm
      - arm64
    goos:
      - linux
      - darwin
    ignore:
      - goos: linux
        goarch: arm64
archives:
  - format: binary
    name_template: >-
      {{ .ProjectName }}_
      {{- if eq .Os "darwin" }}Darwin
      {{- else if eq .Os "linux" }}Linux
      {{- else if eq .Os "linux" }}Linux
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - # Name template of the recipe
    # Default to project name
    name: goer

    # GitHub/GitLab repository to push the formula to
    tap:
      owner: jlec
      name: homebrew-jlec

      # Optionally a token can be provided, if it differs from the token
      # provided to GoReleaser
      # token: "{{ .Env.TAP_GITHUB_TOKEN }}"

    # Allows you to set a custom download strategy. Note that you'll need
    # to implement the strategy and add it to your tap repository.
    # Example: https://docs.brew.sh/Formula-Cookbook#specifying-the-download-strategy-explicitly
    # Default is empty.
    download_strategy: GitHubPrivateRepositoryReleaseDownloadStrategy

    # Allows you to add a custom require_relative at the top of the formula
    # template.
    # Default is empty
    custom_require: ../custom_download_strategy/private

    # Folder inside the repository to put the formula.
    # Default is the root folder.
    folder: Formula

    # Your app's homepage.
    # Default is empty.
    homepage: "https://github.com/{{ .Env.GITHUB_REPOSITORY }}"

    # Your app's description.
    # Default is empty.
    description: "TF provider for Turing PI BMC"

    # SPDX identifier of your app's license.
    # Default is empty.
    license: "Apache-2.0"
