---
name: Continuous Delivery

# yamllint disable-line rule:truthy
on:
  # yamllint disable-line rule:empty-values
  workflow_dispatch:

  push:
    branches:
      - main

permissions: read-all

jobs:
  goreleaser:
    name: "GO Releaser"
    if: >-
      startsWith(github.event.head_commit.message, 'bump:')
    uses: jlec/github-actions/.github/workflows/reusable-cd-go.yml@main
    permissions:
      contents: write
      statuses: write
    secrets:
      pat: ${{ secrets.PAT_GITHUB_TOKEN }}
      token: ${{ secrets.GITHUB_TOKEN }}
      tfe_release_token: ${{ secrets.TFE_RELEASE_KEY }}
      gpg_release_key: ${{ secrets.GPG_RELEASE_KEY }}
  release-and-clean:
    name: Release the code & clean up
    if: >-
      startsWith(github.event.head_commit.message, 'bump:')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      statuses: write
    needs:
      - goreleaser
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}
      - name: Cleanup action status
        uses: ouzi-dev/commit-status-updater@v2
        with:
          status: "success"
          token: ${{ secrets.GITHUB_TOKEN }}
          name: "GithubActions - ${GITHUB_WORKFLOW}"
          ignoreForks: true
